### ISSUE TITLE
Fix occasional NullPointer on JSON parsing

### ISSUE THREAD

**Issue by GustavoAC** [YuriAlessandro/SigEstagios#30]
O JSONObject passado no onPostExecute do AsyncTask chamado GetReq ~~nome terrível~~ vem como null às vezes.
Investigar se pode vir nulo e, se for o caso, fazer o tratamento necessário.

**Comment by YuriAlessandro** [comment]
Eu acredito que ele vem null e um log é lançado no terminal. Mas eu creio que so acontece quando a api do sigaa cai
